### ISSUE TITLE
Настроить автоматические бекапы

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#10]
В `~/private` лежат какие-то бекапы `a70553_lw_2016-12-09_17_00.zip` (mysql-база) и `lesswrong.ru_2016-12-09_17_00.zip` (drupal-сайт), которые делал не я. Либо хостинг их делает изредка сам (но они устарели на два месяца), либо они делаются по кнопке из админки, к которой у меня нет доступа.

Я когда-то написал скрипт `~/private/full-backup.sh`, который бекапит базу и сайт, и запускаю его вручную перед крупными изменениями.
Надо всё это автоматизировать.

Варианты:
* дождаться #7, переезда на VPS
* выяснить у Юлия, можно ли настроить бекапы на макхосте
* повесить где-нибудь скрипт на кроне, который будет делать `ssh lesswrong.ru ~/private/full-backup.sh` раз в сутки.

Ещё хорошо бы, чтобы бекапы копировались куда-то ещё, а не хранились на той же машине. (На S3, например.)

**Comment by kergma-lw** [comment]
Настроил бэкап всех баз данных и кода сайтов на свой сервер бэкапа.  Доступы выданы @berekuk
