### ISSUE TITLE
Добавить на сайт раздел с видео

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#13]
Это не очень важная задача, потому что можно просто в нужных местах ставить ссылки на youtube-плейлисты, но например курс [рациональности для начинающих](https://www.youtube.com/playlist?list=PLl-Tj9sXiROYR97C-th5XyQE4oeWcA15w) вроде получился достаточно ценным, чтобы его положить в отдельный раздел.

Ну и плейлисты со встреч тоже стоило бы подшивать к встречам через embed, а не простой ссылкой.

**Comment by berekuk** [comment]
Учитывая неопределённость между друпал-сайтом и вики, я пока думаю, что на движке друпала это делать не надо. Всё равно собственный контент на вики весь выкладываем.

**Comment by berekuk** [comment]
На вопрос: речь про поле со ссылкой на youtube, хранить у себя видео мы конечно не будем.

**Comment by kergma-lw** [comment]
Тогда поле с ютуб-ссылкой я могу реализовать легко. Очевидно, внутри типа контента "Видео". Делать?

**Comment by kergma-lw** [comment]
Закрываю, чтобы не мешалась.
