### ISSUE TITLE
Прикрутить логин через соцсети

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#23]
С помощью [hybridauth](https://www.drupal.org/project/hybridauth), видимо.

**Comment by kergma-lw** [comment]
Пока что аккуратно включил модуль hybridauth и его либу. Никуда в интерфейсе ещё не высунул.

**Comment by kergma-lw** [comment]
Вот тут https://lesswrong.ru/admin/config/people/hybridauth около каждого провайдера есть ссылка настроек на соответствующее приложение для данного  провайдера. Если я правильно понимаю, создать/зарегистрировать данные приложения лучше Славе.
