### ISSUE TITLE
Поддержать инлайновые картинки в статьях и переводах

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#24]
Сейчас, чтобы добавить картинку к статье, приходится её добавлять к странице [/список-картинок](http://lesswrong.ru/%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D0%BA), а потом уже добавлять вручную ссылку на файл.

Потому что:
* у типа "Переводы" вообще нет поля "Картинка"
* у типа "Статья" есть поле "Картинка", но отображается оно всегда сверху, а не инлайново

Что надо сделать:
* добавить к типу "Переводы" поле "Картинка"
* убедиться, что нигде нет картинок, кроме /список-картинок (например, проверив все файлы в `sites/default/files/images`)
* настроить WYSIWYG для инлайновых картинок; полезные модули: [Insert](https://www.drupal.org/project/insert), [Media](https://www.drupal.org/project/media), [IMCE](https://www.drupal.org/project/imce)
* отключить показ картинок для статей по умолчанию
* переподшить все картинки к соответствующим статьям
* удалить /список-картинок

Вот вроде неплохая инструкция: https://groups.drupal.org/node/300483

**Comment by berekuk** [comment]
И ещё ссылка из закладок: http://donmorris.com/on/markdown-images-and-drupals-image-styles

**Comment by kergma-lw** [comment]
Добавил в "Переводы" поле "внутритекстовые иллюстрации" и настроил его для вставки изображений в текст.

**Comment by kergma-lw** [comment]
Подшил картинки со /список-картинок к странице эмодзи слака. Там явно не все, но это за пределами данной задачи. Больше в /список-картинок ничего не осталось.  Удалять /список-картинок и закрывать задачу?

**Comment by berekuk** [comment]
Ага.
