### ISSUE TITLE
Проинтегрировать форму приглашения в слак на сайт

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#28]
Текущая форма работает через [slackin](https://github.com/rauchg/slackin). Но он требует ноды, тяжеловесный, и работает на отдельном хосте.

Проще поставить https://www.drupal.org/project/slack_invite и показывать форму прямо на http://lesswrong.ru/slack.

**Comment by kergma-lw** [comment]
@berekuk https://lesswrong.ru/admin/config/services/slack_invite сюда надо ввести настройки, которые мне неизвестны.

**Comment by kergma-lw** [comment]
У формы приглашения верстка разносит колонки вширь, поэтому пока поставил над текстом на странице http://lesswrong.ru/slack . Когда ты настроишь нужные параметры и проверишь собственно работу формы, задачу можно будет закрывать (только поправить текст -- убрать оттуда ссылку на текущую форму).

**Comment by berekuk** [comment]
Ок, форму я включил, и похоже она работает. Ура :)

Но у меня вопрос: можно всё же встроить форму в середину страницы? Как это делается? Как-то через токены и надо какой-то ещё модуль ставить, да?

Вёрстку-то я поправлю, это не проблема. Хочется, чтобы форма всё же была после призыва читать правила, а не в самом верху.
