### ISSUE TITLE
Прикрутить рейтинги к переводам (для оценки качества переводов)

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#30]
Вроде как для этого достаточно настроить [fivestar](https://www.drupal.org/project/fivestar), и можно надеяться, что какое-то время спустя у нас появится список наиболее нуждающихся в редактуре текстов.

**Comment by kergma-lw** [comment]
Надо както в админку вывести список этих самых "наиболее нуждающихся" текстов. Куда?

**Comment by berekuk** [comment]
А какие варианты есть?

**Comment by kergma-lw** [comment]
а) в блок слева, видим лишь редакторам;
б) поставить нашу "красную админку", где на одной странице все ссылки, нужные конкретной роли. Туда вписать в том числе ссылку на список этих текстов.

**Comment by berekuk** [comment]
Я не видел красную админку, так что я вяло за (а), но если ты сделаешь (б) и у меня от неё не вытекут глаза, то я тоже согласен.

**Comment by kergma-lw** [comment]
Ну, легче (а), конечно. Второе годится для сайтов, где редакторов немного и у них практически нет опыта. Защита системы от идиота :).

**Comment by kergma-lw** [comment]
Сделал блок слева. Виден редакторам и администраторам.
Сейчас ввиду отсутствия оценок как таковых -- не показывается вовсе :).
