### ISSUE TITLE
Ссылка на slack-профиль из профиля на сайте

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#31]
Сейчас "ник в slack-чате" - текстовое поле. Надо, чтобы в вёрстке профиля подставлялась ссылка `<a href="https://lesswrongru.slack.com/team/USERNAME">`.

**Comment by kergma-lw** [comment]
Использовал модуль custom formatters, чтобы не лезть в вёрстку.
