### ISSUE TITLE
Проблемы при добавлении комментариев

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#32]
Багрепорт:

`The following error messages appear when i tried send comment at
the webpage http://lesswrong.ru/node/133/talk#comment-111:
Notice: Undefined index: mollom в функции mollom_validate_captcha() (строка 2299 в файле /home/httpd/vhosts/lesswrong.ru/httpdocs/sites/all/modules/mollom/mollom.module).
Notice: Undefined index: mollom в функции mollom_validate_captcha() (строка 2310 в файле /home/httpd/vhosts/lesswrong.ru/httpdocs/sites/all/modules/mollom/mollom.module).
Notice: Undefined index: mollom в функции mollom_validate_analysis() (строка 2127 в файле /home/httpd/vhosts/lesswrong.ru/httpdocs/sites/all/modules/mollom/mollom.module).
Notice: Undefined index: mollom в функции mollom_validate_post() (строка 2452 в файле /home/httpd/vhosts/lesswrong.ru/httpdocs/sites/all/modules/mollom/mollom.module).`

**Comment by kergma-lw** [comment]
А это вообще актуально?

**Comment by berekuk** [comment]
Не знаю. Видимо, нет, раз комменты мы всё равно собираемся закапывать в текущем виде.
