### ISSUE TITLE
Обновить базу: MySQL -> MariaDB

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#35]

**Comment by berekuk** [comment]
Первая попытка (5.7 -> 10.1) эпично провалилась. Полчаса простоя сайта. Хорошо хоть что хватило мозгов забекапить всё перед обновлением.

[Разбор полётов](https://lesswrongru.slack.com/archives/C0G0Z4A9H/p1490562712896989):
1) MariaDB 10.1 _не ставится_ поверх MySQL 5.7, несмотря на то, что по https://mariadb.com/kb/en/mariadb/mariadb-vs-mysql-compatibility/#incompatibilities-between-mariadb-101-and-mysql-57 они вроде как должны быть совместимы. Не просто ставится, а отказывается запускаться.
2) После того как я обнаружил, что запустить не получается, погуглил и не нашёл ничего лучше, чем снести /var/lib/mysql, у меня не вышло накатить на MariaDB бекап. То есть накатить-то получилось, но после этого FLUSH PRIVILEGES начал выдавать Unknown error. Видимо, формат mysql.user или ещё какая-то mysql.* у них разный.
3) После того как я решил, что 15-20 минут простоя сайта - это уже слишком, и надо откатываться, ещё довольно долго я бился с тем, что после отката MySQL 5.7 тоже отказался подниматься с полу-проапгрейженной базой. В итоге я ещё минут 15 провёл в цикле “apt-get remove —purge, apt-get install, ой ничего не запускается, purge, rm -rf /var/lib/mysql, install, ой mysql-common остался от mariadb, вычистить из /etc/apt/sources.list, purge, install опять"

**Comment by kergma-lw** [comment]
Судя по `Версия СУБД	5.5.5-10.2.13-MariaDB-10.2.13+maria~xenial-log` в отчёте о состоянии, эту задачу можно закрыть.
