### ISSUE TITLE
При входе на сайт происходит редирект на страницу профиля

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#37]
При входе на сайт происходит редирект на страницу профиля. Хотелось бы оставаться на той странице, на которой ты находился в тот момент, когда решил залогиниться.

**Comment by kergma-lw** [comment]
Сделано.

**Comment by AlaricLightin** [comment]
Похоже, исправления отвалились, опять происходит редирект на страницу профиля.

**Comment by kergma-lw** [comment]
Впечатление, что переключили тему. Так как я мало понимаю тонкость переключения тем с применением Makefile, то лучше посмотреть @berekuk -- в моём репо код правильный.
