### ISSUE TITLE
Установить полезные расширения к вики

### ISSUE THREAD

**Issue by fpaint** [lesswrong-ru/lesswrong-ru#38]
Список полезных расширений, которые надо поставить, тут: http://lesswrong.ru/forum/index.php?topic=1122.msg32448#msg32448

**Comment by berekuk** [comment]
И ещё: https://github.com/grundleborg/mediawiki-slack

**Comment by berekuk** [comment]
- [ ] Interwiki
- [ ] NewestPages
- [ ] AddBodyClass
- [ ] ParserFunctions
- [ ] Cite
- [ ] EmbedVideo
- [ ] MultimediaViewer
- [ ] WikiEditor

И ещё поставил Math (работает через Mathoid и внешний сервис).
