### ISSUE TITLE
Починить генерацию книг

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#41]
На старом хостинге был скрипт makebook.sh, его надо приспособить к новому хостингу, поставить calibre и html2fb и обновить список книг.

**Comment by berekuk** [comment]
Юлий говорит, что ещё при этом надо будет сделать файл типа такого: http://hpmor.ru/files/opds2.xml.
И либо сдать ему, либо выложить куда-нибудь на lesswrong.ru, чтобы он импортировался потом на hpmor.ru.

**Comment by berekuk** [comment]
`makebook.sh` лежит в `/home/berekuk/books`.

**Comment by kergma-lw** [comment]
Судя по makebook.sh, основную работу выполняли скрипты в каталоге /users/berekuk/private/html2fb. Если этого каталога нигде не сохранилось, придётся генерацию книг писать с нуля.

**Comment by berekuk** [comment]
Каталог был на старом хостинге, но к тому времени, как я про него вспомнил, он оттуда почему-то исчез. Подозреваю, что Юлий чистил место и удалил, но я не спрашивал.

Ещё очень подозреваю, что в этом каталоге был этот софт: https://code.google.com/hosting/moved?project=html2fb
Но, как можно узнать, пройдя по ссылкам, его 9 лет не обновляли, и видимо лучше обновить makebook, сделав его совместимым хотя бы с https://github.com/trousev/html2fb2. Подробнее не разбирался.

**Comment by kergma-lw** [comment]
Я постараюсь уделить этому время на неделе -- есть острое чувство, что это обернётся весьма заметным развлечением.

**Comment by kergma-lw** [comment]
Поставил на хостинг python-pil.imagetk.

Довёл скрипт /home/berekuk/books/makebook-new.sh до генерации одного как-бы-правдоподобного fb2.zip архива. Мне остаётся воспроизвести заново утраченный скрипт чистки исходного html от ненужного в книге текста ссылок и т.д.

**Comment by kergma-lw** [comment]
Добавил немного чистки.
http://lesswrong.ru/files/Свежий_взгляд_на_вещи.new.tmp.fb2.zip в моём fbreader читается почти нормально.
Пока не понял, делались ли теги section утраченным скриптом чистки или этого можно добиться ключами html2fb2. Также не совсем понятно, как выводить html entities.

**Comment by berekuk** [comment]
А ты сравнивал, чем оно отличается (и отличается ли) от того, что на сайте?

**Comment by kergma-lw** [comment]
Ну вот сейчас я вроде бы довёл до очень похожего с тем, что на сайте, состояния. 

Изрядно смущает то, что и у меня, и у книги на сайте в fb2 отсутствует метаинформация о книге: автор, жанр и т.д.

**Comment by berekuk** [comment]
Кстати, если всё уже не хуже, чем было, можно уже ставить на крон автогенерацию, наверное?

И ещё: закоммитишь код? Можно прямо в этот репозиторий, думаю.

**Comment by kergma-lw** [comment]
Автора и название я в метаинформацию научился вставлять.

Остаётся проблема с аннотациями. Это заметно там, где нужно выводить аннотацию к книгам. Решим её и можно будет думать про автогенерацию и коммиты.

Аннотации, судя по всему, вставляет строчка https://github.com/trousev/html2fb2/blob/master/h2fb.py#L869 , но мне не хватает знаний питона, чтобы понять, как выглядит тот html, откуда берётся аннотация.

**Comment by kergma-lw** [comment]
В итоге я нашёл грубую ошибку в строке извлечения аннотации -- функция питона rstrip('</section>') делает совершенно не то, что подразумевается -- и поправил код html2fb2.

**Comment by kergma-lw** [comment]
Я довёл тестовую книгу http://lesswrong.ru/files/%D0%A1%D0%B2%D0%B5%D0%B6%D0%B8%D0%B9_%D0%B2%D0%B7%D0%B3%D0%BB%D1%8F%D0%B4_%D0%BD%D0%B0_%D0%B2%D0%B5%D1%89%D0%B8.new.tmp.fb2.zip до состояния, которое считаю удовлетворительным. Просьба подтвердить мою оценку или написать замечания.

**Comment by kergma-lw** [comment]
Поставил в /etc/cron.daily/makebook пересборку книг. Забавно, что при этом всплыла ещё одна неточность в html2fb2 касательно скачивания внутритекстовых  картинок и пришлось снова править код html2fb2.

**Comment by kergma-lw** [comment]
Сделал генерацию http://lesswrong.ru/files/opds2.xml

**Comment by kergma-lw** [comment]
Внёс код в репозиторий. Рекомендую обратить внимание на https://github.com/lesswrong-ru/generate-books/blob/master/makebook-new.sh#L33 -- эта строка закомментирована, потому что я не нашёл нигде на сайте  ничего похожего на книгу "Самодостаточные материалы". В остальном задача выполнена полностью.
