### ISSUE TITLE
Настроить интеграцию drupal<->mediawiki

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#44]
В первую очередь про авторизацию, но остальное тоже стоит посмотреть.
https://www.drupal.org/project/mediawikiauth
https://www.drupal.org/project/mediawiki
https://www.drupal.org/project/mediawiki_api
https://www.mediawiki.org/wiki/Extension:AuthDrupal (unmaintained)

**Comment by kergma-lw** [comment]
Пока просто присвоил задачу себе. Надо вникать.

**Comment by kergma-lw** [comment]
Три ссылки из четырёх ведут на брошенные проекты. Вероятность того, что всё это вместе сходу заработает, я оцениваю невысоко. Что это _продолжит_ работать -- ещё ниже.

Рекомендация: составить перечень того, для чего сейчас применяется медиавики, и того, для чего применяется друпал. Затем повторить процедуру для будущих применений. Сравнить списки и выбрать одну из систем для _всего..

**Comment by berekuk** [comment]
Друпал надо _очень долго_ допиливать до функционала (и удобства) медиавики.
Медиавики не очень-то годится для создания красивых медийных сайтов.

Друпал в долгосрочной перспективе мне всё же хочется выпилить. Я не думаю, что через 5 лет он ещё будет актуальным, я ожидаю, что он продолжит отставать даже от вордпресса, не говоря уж о том, что придёт вслед за вордпрессом.

Медиавики заменить особо не на что. На какую-нибудь другую вики, но все остальные заметно отстают по функционалу и менее привычны среднему пользователю.

Из будущих применений - я бы хотел на сайте иметь новый клёвый форум. Для друпала хороших решений нет, для вики тоже, так что всё равно придётся что-то кодить или внедрять внешнее. Короче, мне видится "самописный движок + медиавики" или "какой-то static site generator + медиавики" или в крайнем случае "wordpress rest api + самописный фронтенд + медиавики".

На эту задачу предлагаю пока что забить.
