### ISSUE TITLE
Включить логи с таймингами php-fpm

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#46]
Сайт иногда ложится и тормозит, не очень понятно, почему.
Надо почитать `/etc/php/7.0/fpm/php-fpm.conf` и включить там логгирование времени ответа.

**Comment by kergma-lw** [comment]
Я не нашёл там логгирования времени ответа. Попытался в мыскле включить логгирование медленных запросов, но он меня не понял. Попробую снова позже.

**Comment by kergma-lw** [comment]
Уговорил mysql писать лог медленных запросов в /var/log/mysql/mysqld-slow-query.log

**Comment by kergma-lw** [comment]
Подкрутил конфиг мыскля:

innodb_flush_log_at_trx_commit=2
query_cache_type        = ON
query_cache_limit       = 3M
query_cache_size=128M

**Comment by kergma-lw** [comment]
Честно сказать, склонен закрыть задачу. Логи php-fpm нам нужны были для анализа падений. а сейчас и бд и буст настроены  по максимум, большего особенно не выжмешь.
