### ISSUE TITLE
Найти способ включить drupal block cache

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#47]
Сейчас его нельзя включить из-за content access.

https://drupal.stackexchange.com/questions/1651/why-cant-i-disable-or-enable-the-block-cache - тут советуют поставить Block Cache Alter, надо разобраться, что он делает, безопасно ли его ставить, и поставить.

**Comment by kergma-lw** [comment]
Судя по документации, он ускоряет именно для залогиненных пользователей. Какого-то ущерба безопасности я не увидел. Могу поставить и поиграться, сделав предварительно бэкап, конечно.

Делать?

**Comment by berekuk** [comment]
Да, давай попробуем.

**Comment by kergma-lw** [comment]
Поставил Block cache alter. Включил кеширование по ролям для трёх блоков слева на главной. Если за два дня не будет жалоб на странное, закешируюю ещё блоков.

**Comment by kergma-lw** [comment]
Похоже, работает.
