### ISSUE TITLE
Сделать кнопку Share in для соцсетей

### ISSUE THREAD

**Issue by fil0sof** [lesswrong-ru/lesswrong-ru#48]

**Comment by kergma-lw** [comment]
Можно ли подробнее? Я вижу, что _кое-где_ такие кнопки уже есть. Имеется в виду сделать такое у всех материалов?

**Comment by fil0sof** [comment]
Когда я этот айтем заводил, я нигде не видел этих кнопок. Сейчас несколько
штук рандомно открыл, у некоторых действительно есть. Видимо, в новые
переводы руками добавляли

2018-01-22 12:18 GMT+03:00 kergma-lw <notifications@github.com>:

**Comment by berekuk** [comment]
Не представляю механизма, как такое можно добавить вручную. Можно ссылки?

Я вижу только кнопки шаринга в соцсетях на главной. Которые, кстати, надо бы выпилить или переделать, потому что они вырвиглазно свёрстаны, все разных размеров.

**Comment by fil0sof** [comment]
Эмм.. Я сейчас сходу эту переписку в слаке не найду (возможно по дате
заявки можно, но у меня сейчас нет времени), но я тогда написал тебе (вроде
в ордер), спросил, почему нет кнопок шаринга и можно ли их легко приделать,
ты сказал, что можно, и попросил завести таску в гите, собственно, что я и
сделал :)

2018-01-22 15:21 GMT+03:00 Vyacheslav Matyukhin <notifications@github.com>:

**Comment by berekuk** [comment]
Я имел в виду не это, я про это вот:
> Сейчас несколько штук рандомно открыл, у некоторых действительно есть
На каких страницах есть кнопки шаринга? Можно ссылки?

**Comment by kergma-lw** [comment]
Поставил AddtoAny и сделал кнопки шаринга для ВК, Одноклассников, ФБ  и Твиттера.

**Comment by berekuk** [comment]
Может, нафиг Одноклассников? :) Пересечение с их аудиторией у нас примерно нулевое.

**Comment by kergma-lw** [comment]
Как  именно на главную ввёрстаны вырвиглазные кнопки, я сходу не понял.

**Comment by kergma-lw** [comment]
Я не вижу причин, по которым стоит специально игнорировать огромное поле пусть, эээ, малоразумных, но всё же людей. В конце концов продиффундируем и в одноклассники :).

**Comment by berekuk** [comment]
На главной кнопки через service links + russian services, насколько я понимаю.

Причина - любая лишняя кнопка на странице имеет цену (перегружает интерфейс), а ещё конкретно иконка одноклассников по-моему влияет на восприятие всего сайта в целом, потому что свитедельствует об их целевой аудитории. А ещё она более яркая, чем остальные.

А ещё вангую, что ей никто никогда не воспользуется (меньше 1% от всех шар в ближайший год).

Давай уберём.

**Comment by kergma-lw** [comment]
Про репутационные издержки в данном ракурсе я в самом деле не подумал. Убедил. Убрал.

Вырвиглазное убрал.
