### ISSUE TITLE
Перенести уведомления о новых переводах и новых редакциях в отдельный канал slack'а

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#50]
Канал #translations slack'а иногда слишком забивается уведомлениями. Лучше было бы, если бы уведомления о новых переводах и новых редакциях отправлялись бы в отдельный канал - по аналогии как существуют #wiki и #wiki_recent_changes.

**Comment by berekuk** [comment]
Готово, канал #translations_changes.
