### ISSUE TITLE
Изменить вёрстку главной страницы для создания остальных томов RfAZ

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#51]
В обсуждении в #order 30.06.17 мы пришли к выводу, что имеет смысл сделать только две корневые страницы подшивки - одну для книги Rationality: From AI to Zombies, другую для всего остального. (Позже поступило предложение, что лучше три - одну отдельную для всех прочих статей с lesswrong.com.) 

Для этого нужно поправить вёрстку/стили главной страницы, чтобы они были совместимы с новой структурой.

**Comment by kergma-lw** [comment]
Собственно, я частично это уже сделал -- переделал структуру. Что ещё можно сделать по данной задаче?

**Comment by berekuk** [comment]
Не, можно закрывать.
