### ISSUE TITLE
Показывать в переводах из R:fAtZ ссылки на readthesequences.com

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#54]
Сейчас во всех переводах указывается ссылка на оригинал, и в переводах из книги R:fAtZ как оригинал указывается страничка с lesswrong.com. 

Однако, когда Юдковский оформлял цепочки в книгу, он кое-что всё-таки подправил. И мы у себя на сайте утверждаем, что мы выкладываем перевод именно книги. Поэтому было бы неплохо в качестве оригиналов указывать книгу.

Можно было бы просто заменить все ссылки на lesswrong.com на соответствующие ссылки на readthesequences.com (для эссе из книги), однако, @berekuk как-то заметил, что на страницах lesswrong.com есть и ценные комментарии к цепочкам, и их тоже стоило бы сохранить. Поэтому, видимо, необходимо иметь две ссылки на оригинал - на оригинальную цепочку и на окончательный текст книги.

**Comment by kergma-lw** [comment]
Поле я сделал. Теперь надо кого-то посадить за расстановку ссылок...

**Comment by AlaricLightin** [comment]
Замечательно, но в текущем виде выглядит несколько странно. После заполнения полей, пользователь увидит два, как я понимаю, всегда одинаковых названия друг под другом. По-моему, надо всё-таки писать пояснения вроде "Ссылка на оригинал на lesswrong.com", "Ссылка на текст книги на readthesequences".

Как я понимаю, это связано с трудностью, что надо отличать то, что входит в книгу от того, что в книгу не входит. Но сейчас это, по идее, можно определить по тому, в какой ветке находится перевод.

Также, наверное, стоит сгруппировать новые поля и номер в книге, и, по возможности, вообще не показывать все эти поля, если речь о тексте не из книги.

**Comment by kergma-lw** [comment]
@AlaricLightin как-то так? https://lesswrong.ru/w/%D0%9E%D0%B1%D1%8B%D0%B4%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D0%B3%D0%B8%D1%8F
