### ISSUE TITLE
Поддержать загрузку аудиозаписей

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#55]
Во-первых, для аудиоверсий цепочек - https://vk.com/wall-65688570_3753.

Во-вторых, возможно, в будущем запишем подкаст =)

**Comment by kergma-lw** [comment]
Сделал тип контента. Создал роль "редактор аудио" и выдал ей права.  Разбираюсь с лимитом php на заливку.

**Comment by kergma-lw** [comment]
Увеличил лимит php на заливку файлов. Сейчас он 200M.

**Comment by kergma-lw** [comment]
Добавил на сайт четыре присланных Даниилом Храмцовым аудио и привязал их к соответствующим статьям.
