### ISSUE TITLE
Добавить блок "свежие переводы"

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#6]
Сабж. Куда добавлять — пока не знаю. Можно наверх блока с переводами, можно в левую колонку. Технически это реализовать несложно через views.

**Comment by berekuk** [comment]
Из отзывов к [survey-2015](http://lesswrong.ru/survey/2015/):
> На сайте lesswrong.ru не понятно появилась ли новая статья или нет

**Comment by kergma-lw** [comment]
Не пора ли закрывать эту задачу?

**Comment by berekuk** [comment]
Да, пора.
