### ISSUE TITLE
Генерация книг - Ошибка в заголовке

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#62]
В автоматически генерируемой книге в формате fb2 в заголовок (тэг book-title) попадает строчка "| LessWrong на русском", что явно неправильно.

Кроме того, в тэге title сейчас записана аннотация, сомневаюсь, что это правильно.

**Comment by kergma-lw** [comment]
> В автоматически генерируемой книге в формате fb2 в заголовок (тэг book-title) попадает строчка "| LessWrong на русском", что явно неправильно.

Исправил.

**Comment by kergma-lw** [comment]
> Кроме того, в тэге title сейчас записана аннотация, сомневаюсь, что это правильно.

Исправил.
