### ISSUE TITLE
Генерация книг - проблема с внутренними ссылками

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#63]
В RfAtZ много внутренних ссылок (ссылок на другие главы). Сейчас при генерации fb2 они превращаются в интернет-ссылки, что довольно неудобно, если человек читает книгу с читалки, например. Нельзя ли делать так, чтобы ссылки на уже имеющиеся переводы других глав вели не в интернет, а оказывались бы перекрёстными ссылками?

**Comment by kergma-lw** [comment]
Я подготовил в тексте внутренние якоря на начала глав на основе nid. К сожалению, я обнаружил, что почти все внутрисайтовые ссылки -- длинные, а не короткие (которые тоже на основе nid). Таким образом, их нельзя дёшево преобразовать во внутритекстовые ссылки. Теоретически способы есть, но все они сравнительно дорогие. Я продолжу размышлять на эту тему.

**Comment by kergma-lw** [comment]
Сделано.Такие внутритекстовые ссылки в полном тексте Цепочек помечены значком →.

**Comment by AlaricLightin** [comment]
По-моему, преобразовалось далеко не всё. Собственно, если открыть fb2 как plain text и сделать поиск по lesswrong.ru можно найти достаточно случаев непреобразованных ссылок. (Некоторые из них ведут на "прочие материалы" и потому не в счёт, но не все).

Кроме того, кажется, перестали работать сноски. Можно проверить даже на сносках в "Искажения: введение", там их много.

Насчёт значка не очень понятно. У меня в одной программе (Haali Reader) он есть, в другой (STDUViewer) и на читалке - нет. Впрочем, я не уверен, что выделять ссылки значком - это хорошая идея. Поскольку ссылки вписаны в текст, значок несколько отвлекает.

**Comment by kergma-lw** [comment]
Убрал значок.

Несколько увеличил количество преобразованных ссылок.

Над остальным думаю.

**Comment by kergma-lw** [comment]
Я изучил код сносок. У меня сильная уверенность (>90%), что сноски в сгенерированном fb2 вообще никогда не работали. Буду рад опровержению и, ещё более, fb2 с рабочими сносками.

**Comment by AlaricLightin** [comment]
[Тестовая fb2.txt](https://github.com/lesswrong-ru/lesswrong-ru/files/2438002/fb2.txt)
Соорудил тестовую fb2 со сноской (расширение пришлось переделать в txt, потому что иначе github отказывался грузить файл). В Haali Reader и FBReader сноска работает.

**Comment by kergma-lw** [comment]
Сделал сноски из текста на сноску. Обратные ссылки из сноски в текст пока не работают.

**Comment by kergma-lw** [comment]
Обратные ссылки из сноски теперь почти всегда работают.

Известное исключение, когда в целевом абзаце не одно примечание, а несколько. Тогда работает только возврат на первую сноску в данном абзаце. Это можно видеть, если покликать по сноскам в абзаце со словами "обдумывали своё решение." -- сноски 3, 4, 5 все работают, но из сносок возвращает лишь на сноску 3. @AlaricLightin , если исследуешь,  в честь чего такое, и сможешь посоветовать путь обхода, буду рад.

**Comment by AlaricLightin** [comment]
Обратные сноски, по-моему, вообще не слишком критичны, потому что читалки и программы для чтения вроде бы умеют обрабатывать возврат самостоятельно (хотя я не в курсе, насколько многие). Если хочется пофиксить проблему, то надо сделать так, чтобы в обратных ссылках правильно стояли идентификаторы (сейчас идентификатор исходного абзаца и идентификатор ссылки строятся на основании общего "суффикса", но идентификатор у абзаца может быть только один, поэтому если ссылок в абзаце несколько обратные ссылки получаются на несуществующий абзац).

Просьба по косметическому изменению, с моей точки зрения, достаточно важная. Хотелось бы, чтобы сноски выделялись в тексте, хотя бы уходом в верхний регистр (superscript). Сейчас на чёрно-белой читалке они сливаются с текстом.

**Comment by kergma-lw** [comment]
Сделал superscript. Закомментировал код, создающий обратные ссылки.

@AlaricLightin , закрой задачу, если всё хорошо.
