### ISSUE TITLE
Неправильно строится оглавление разделов в переводе

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#69]
Пример: https://lesswrong.ru/w/Книга_об_интересных_и_здоровых_встречах
В переводе есть разделы первого и второго уровня. В оглавление попали только разделы второго уровня.

**Comment by AlaricLightin** [comment]
Дополнение: вся страница выдаёт ошибку 
Warning: DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 65 в функции simple_table_of_contents_generate_table_of_contents() (строка 108 в файле /srv/lesswrong.ru/sites/all/modules/simple_table_of_contents/simple_table_of_contents.module).

**Comment by berekuk** [comment]
> Unexpected end tag : p in Entity

Бинарный поиск проблемного участка показал, что дело во вложенном списке в секции “Место” (после “Желательно, чтобы место встречи было:“). Виноват модуль simple_table_of_contents, но отключать его, наверное, не стоит.

Хорошо бы его заменить на какой-то другой модуль генерации оглавления. Вот тут собраны альтернативы: https://www.drupal.org/node/2278811.

**Comment by berekuk** [comment]
Я отключил отображение ошибок в продакшне, проблемы больше нет =)
