### ISSUE TITLE
Перенести сайт на отдельный VPS

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#7]
Сейчас lesswrong.ru работает на виртуальном хостинге от [макхоста](https://mchost.ru/).

Зачем переезжать:
* будет работать drush
* больше производительности
* больше контроля над средой, базой, бекапами и т.п.
* можно будет настроить https

**Comment by berekuk** [comment]
Подзадачи:

- [ ] обсудить с Юлием
- [ ] поднять виртуалку (AWS? DO? какой-нибудь Hetzner или прочие дешёвые хостеры?)
- [ ] поднять apache/nginx, mysql, настроить php
- [ ] выложить базу (сайта и форума) и файлы
- [ ] настроить почту
- [ ] убедиться, что всё работает
- [ ] ещё раз накатить базу и сайт
- [ ] переключить DNS

Есть задачи, связанные с этой, но которые не обязательно делать одновременно:
- #8 (перейти на php 7)
- #10 (автоматические бекапы)
- #25 (организовать git-репозиторий)
- настройка drush

Поскольку и так будет с чем повозиться, то осмысленнее сначала переехать на VPS, а потом уже улучшать инфраструктуру на новом месте.

**Comment by Tairesh** [comment]
Предлагаю дроплет за $5 в месяц на DO с убунтой. На нём поставить lnmp с седьмым пхп дело получаса. Возможно придётся поковыряться с настройками nginx, чтобы перенаправления и подобные штуки их .htaccess перенести. С 90% вероятностью одного вечера хватит.
Что имеется ввиду под настройкой почты.

**Comment by berekuk** [comment]
Про почту - ну, текущий lesswrong.ru каким-то образом умеет отправлять письма. Насколько я представляю устройство мира, в 2017-м нельзя просто так отправлять письма по SMTP (очень плохо будет с доставкой), нужен Mailgun или Amazon SES или что-то в этом роде.

Как это в drupal или php настраивается, я не в курсе.

Про DO ок. Про стек и замену apache->nginx тоже точно очень за. В 512MB точно mysql+nginx+php влезут без проблем (с учётом прочих фоновых процессов, которые надо будет иногда запускать, типа drush, бекапов, тестовой среды)? Поиск по слаку (elastic+node) с трудом влезают в 1GB, например. Я бы перестраховался и взял хотя бы 1GB/$10 всё же.

**Comment by berekuk** [comment]
Поговорил с Юлием, ему ок переезд на VPS.

**Comment by berekuk** [comment]
Всё готово, всё работает, осталось придумать план переезда с минимальным даунтаймом.

**Comment by berekuk** [comment]
План переезда такой:
- [ ] открыть mysql-базу на новом сервере для удалённого доступа (с логином/паролем, естественно)
- [ ] на полчаса заморозить старый сайт (друпал перевести в maintenance mode, форум - ещё не придумал, проще всего погасить)
- [ ] быстро скопировать базы на новый сервер: mysqldump, scp, zcat > mysql
- [ ] переключить координаты базы в settings.php на старом сервере и включить старый сервер обратно
- [ ] проверить, что всё работает
- [ ] написать в слак, чтобы все проверили, что косяков нет
- [ ] попросить Юлия/BT/Матвея переключить DNS

Что мне не нравится в этом плане, хотя это практически неважно:
MySQL по умолчанию гоняет данные по сети без шифрования, но это будет междатацентровый трафик, и на lesswrong.ru всё равно никогда не было https. Короче, я не стал заморачиваться с настройкой SSL для mysql.

**Comment by fpaint** [comment]
Вариант: купить безвентиляторный микрокомп с SSD по цене одного билета на воркшоп, поставить его в уголок в Кочерге и хостить на нём что угодно, сколько угодно, совершенно бесплатно. )
