### ISSUE TITLE
Вывод списка с оценками переводов

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#73]
Хотелось бы иметь возможность ознакомиться с полным перечнем оцененных переводов и отсортировать его по оценке, чтобы видеть, какие именно переводы люди считают наиболее проблемными.

**Comment by kergma-lw** [comment]
Дописал в низ блока с оценёнными переводами ссылку на страницу с полным списком.

Сортировка по оценке чрезвычайно странная, причину пока не понял.

**Comment by AlaricLightin** [comment]
У меня складывается впечатление, что список не полный. Например, у перевода https://lesswrong.ru/w/Убеждения_должны_окупаться оценка не максимальна, но в списке я его не вижу.

**Comment by kergma-lw** [comment]
Фильтры и сортировка по оценкам, похоже, сломаны. Думаю.

**Comment by kergma-lw** [comment]
Выводим сначала переводы с самыми низкими оценками. Возможно, такое поведение стоит уточнить.

**Comment by AlaricLightin** [comment]
У меня в списке по-прежнему нет перевода https://lesswrong.ru/w/Убеждения_должны_окупаться
И список по-прежнему не отсортирован.

**Comment by kergma-lw** [comment]
Я таки раскопал проблему с сортировкой на лессвронге

Там очень неочевидно.

Там надо было во вьюсе создать связь с результатами голосований и сортировать по полю из связи.

Сейчас всё работает.
