### ISSUE TITLE
Сброс оценки переводов

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#74]
В случае масштабной редактуры перевода имеет смысл сбрасывать оценку. Вероятно, имело бы смысл, сделать автоматическое сбрасывание, если содержание меняется "достаточно сильно". Также, возможно, имеет смысл дать администраторам сбрасывать оценку вручную. Возможно, на первых порах достаточно второго.

**Comment by kergma-lw** [comment]
Реализовано для роли administrator. Под опубликованным текстом есть кнопка сброса оценок.

**Comment by berekuk** [comment]
Не вижу кнопки что-то.

<img width="841" alt="Screenshot 2019-04-17 at 12 43 47" src="https://user-images.githubusercontent.com/89368/56278179-79a7fe80-610e-11e9-9798-26d34d9ed5c7.png">

**Comment by kergma-lw** [comment]
https://screenshots.firefox.com/7YMo0NWaps0WTDfL/lesswrong.ru

**Comment by kergma-lw** [comment]
У пользователя berekuk была установлена тема lw_theme25. Тема теперь исправлена и кнопка сброса голосов появилась.

**Comment by berekuk** [comment]
А. @kergma-lw, а как ты исправляешь тему? Прямо на сервере файлы? Если так, то все твои правки рано или поздно исчезнут, потому что я-то из git-репозитория https://github.com/lesswrong-ru/drupal-theme-ng выкатываю.
