### ISSUE TITLE
Отсутствие сортировки в блоке "События в Кочерге" в левой панели

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#76]
В левой панели в блоке "События в Кочерге" события не сортируются по дате, что может быть неудобно.

Предполагаю, что в этом блоке вообще не стоит показывать прошедшие события, а будущие сортировать от наиболее близких по времени к наиболее далёким.

**Comment by berekuk** [comment]
Кажется, благодаря новому полю даты сортировка теперь по дате. Правда, сверху самые далёкие события, но блок в друпале устроен так, что по-простому это не чинится.
