### ISSUE TITLE
На странице "События в Кочерге" выводятся две даты

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#77]
На странице "События в Кочерге" (https://lesswrong.ru/aggregator/sources/3 ) выводятся две даты: как я понимаю, дата добавления события и, собственно, дата события. Предположу, что такая путаница может сбивать читателя с толку. Думаю, дата добавления события обычному пользователю вообще не нужна. Если хочется её оставить, думаю, стоит её выводить как-то менее заметно и с пометкой, что это такое.

Также, возможно, стоит поставить какой-нибудь разделитель между будущими событиями и прошлыми.

**Comment by berekuk** [comment]
Исправил Atom-фид, теперь там дата есть в правильном поле. Про разделитель - по-простому не выйдет.
