### ISSUE TITLE
На странице добавления/редактирования перевода разрастается раздел "Аудио"

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#80]
На странице добавления/редактирования перевода можно к переводу прикрепить аудиозапись. Сейчас это выглядит так, что на каждую существующую аудиозапись на странице появляется чек-бокс. Что в условиях увеличения аудиозаписей увеличивает количество элементов на странице.

Возможно, под аудиозаписи имеет смысл добавить отдельную вкладку внизу страницы (там, где "Информация о редакции", "Настройки адресов" и так далее).

**Comment by niya3** [comment]
@berekuk это в самом деле очень неприятно, вкладка не помещается на экран даже с уменьшенным шрифтом. А через неё приходится проматывать каждый раз, чтобы добраться до управляющих элементов.

![image](https://user-images.githubusercontent.com/1140412/82703394-7ae61c00-9c7c-11ea-830d-7d338bd84f43.png)

**Comment by kergma-lw** [comment]
Сменил на более компактное отображение.

**Comment by niya3** [comment]
@kergma-lw спасибо, так стало гораздо лучше
