### ISSUE TITLE
Генерация книг - неправильно строится оглавление

### ISSUE THREAD

**Issue by AlaricLightin** [lesswrong-ru/lesswrong-ru#84]
Оглавление книги "Рациональность: от ИИ до Зомби" в fb2-файле строится неправильно в 3-м и 4-м томах. Почему-то в оглавление попадают как независимые единицы отдельные подразделы введений Бенсинджера, а цепочки, составляющие том, оказываются "детьми" одного из этих подразделов.
![Оглавление](https://user-images.githubusercontent.com/26712776/81061206-9c08e780-8edc-11ea-92d2-1804109f12dc.PNG)

**Comment by kergma-lw** [comment]
@AlaricLightin 

- на сайте при этом все оглавления правильны?
- можешь на скриншоте пометить, какие части куда включены _неверно_?

**Comment by AlaricLightin** [comment]
Да, на сайте структура сейчас правильная.
![Оглавление с поправками](https://user-images.githubusercontent.com/26712776/81099747-11dc7580-8f14-11ea-8942-b0a30b158301.PNG)

**Comment by kergma-lw** [comment]
Насколько я могу судить, всё исправлено согласно замечаниям на скриншоте.
