### ISSUE TITLE
Запрос: Переименовать лейбл "Оцените перевод"

### ISSUE THREAD

**Issue by niya3** [lesswrong-ru/lesswrong-ru#89]
Периодически встречается ситуация, что у откровенно плохого перевода очень высокий рейтинг (например, 3.7 у https://lesswrong.ru/w/Неограниченные_шкалы_решения_присяжных_и_футуризм , который недавно пришлось частично перевести заново), а у прекрасно переведённого текста - несправедливо низкий (например, 3.2 у https://lesswrong.ru/w/Обыденная_магия ).
Возможно, дело в том, что голосующие оценивают идею оригинала? Может попробовать сместить акценты, и назвать ярлык не "Оцените перевод", а, например "Оцените качество перевода" или "Оцените работу переводчика"?

**Comment by berekuk** [comment]
Хорошая идея, переименовал.
