### ISSUE TITLE
Настроить sitemap.xml

### ISSUE THREAD

**Issue by berekuk** [lesswrong-ru/lesswrong-ru#9]
Вероятно, для этого достаточно поставить модуль [xmlsitemap](https://www.drupal.org/project/xmlsitemap).

**Comment by kergma-lw** [comment]
Настроил модуль. Включил в карту все типы контента, словари и пользователей.

http://lesswrong.ru/sitemap.xml

**Comment by berekuk** [comment]
А есть какие-нибудь идеи, как wiki-страницы туда тоже включить? И форум, вообще-то.
Один sitemap может же ссылаться на другой?
