### ISSUE TITLE
Электронные книги: отображение формул

### ISSUE THREAD

**Issue by niya3** [lesswrong-ru/lesswrong-ru#93]
fb2, Linux + Okulus. В LibreOffice проблема воспроизводится, в Android + fb2reader тоже. Фрагмент взят из https://lesswrong.ru/w/Общая_информация_и_плотность_в_пространстве_вещей

![image](https://user-images.githubusercontent.com/1140412/89826920-97993e00-db5f-11ea-88a8-fed149f88e7c.png)

**Comment by AlaricLightin** [comment]
Вопрос дублирует #65

**Comment by niya3** [comment]
Закрыл как дубликат.
