### ISSUE TITLE
Возможна инъекция в поисковой строке?

### ISSUE THREAD

**Issue by niya3** [lesswrong-ru/lesswrong-ru#95]
запрос в поиске типа `100$` выдаёт https://lesswrong.ru/search/node/^100%24

```
Warning: preg_replace(): Compilation failed: invalid UTF-8 string at offset 5162 в функции search_excerpt() (строка 1256 в файле /srv/lesswrong.ru/modules/search/search.module).
```

Это случайно не эта инъекция? https://www.drupal.org/project/drupal/issues/2508735

**Comment by berekuk** [comment]
Не похоже на конкретно эту инъекцию, у нас php 7.1, по ссылке баг был 5 лет назад и в php 5.4.

В общем, я решил проблему радикально - отключил отображение ошибок :) Потому что на текущем сайте есть несколько таких, при этом мы с ними ничего не делаем, и они ни на что, кажется, не влияют.
